---

- hosts: serversa
  become: true
  tasks:
  - name: Agregar Llave Docker Back
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  - name: Agregar Repositorio Docker
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present
  - name: Instalar Docker
    apt: update_cache=yes name=docker-ce state=latest

  - name: Install docker-compose Back
    remote_user: ubuntu
    get_url: 
      url : https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: 'u+x,g+x'
  - name: Instalar Nodejs backend
    apt: name=nodejs state=present
  - name: Instalar npm backend
    npm:
      name: "npm@latest"
      global: yes
      state: present